apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  ENVIRONMENT: "local"
  LOG_LEVEL: "INFO"
  REDIS_URL: "redis://local-redis:6379/0"
  KAFKA_BOOTSTRAP_SERVERS: "local-kafka:9092"
  ORDER_CREATED_TOPIC: "orders.created"
  JWT_ALGORITHM: "HS256"
  JWT_ISSUER: "order-service"
  JWT_AUDIENCE: "order-service-api"