apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  APP_NAME: "order-service"
  ENVIRONMENT: "local"
  LOG_LEVEL: "INFO"
  REDIS_URL: "redis://redis:6379/0"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  ORDER_CREATED_TOPIC: "orders.created"
  OTEL_ENABLED: "true"
  OTEL_CONSOLE_EXPORTER_ENABLED: "true"
  METRICS_SERVER_ENABLED: "true"
  METRICS_SERVER_PORT: "9000"